version: '3.3'
services:
  express-app:
    container_name: express
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
  hasura-engine:
    image: hasura/graphql-engine:v2.35.0
    container_name: controller
    ports:
      - 8080:8080
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${HASURA_METADATA_DATABASE_URL}
      HASURA_GRAPHQL_DATABASE_URL: ${PG_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_AUTH_HOOK: http://express:${APP_PORT}/verify
      REMOTE_SCHEMA_ENDPOINT: http://express:${APP_PORT}/graphql
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: 'true'
      ACTION_BASE_ENDPOINT: http://express:${APP_PORT}/actions
      EVENT_BASE_ENDPOINT: http://express:${APP_PORT}/events
      CRONJOB_BASE_ENDPOINT: http://express:${APP_PORT}/cronjobs
    depends_on:
      - express-app
