services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/docker-entrypoint-initdb.d/create_hdb.sql:/docker-entrypoint-initdb.d/create_hdb.sql
volumes:
  postgres:
